---
- name: add ssh key
  hosts: ubuntu
  become: yes
  tasks:
  - name: install public keys
    ansible.posix.authorized_key:
      user: "{{ lookup('env','HOME') }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  - name: change sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s
